name: make_clash

on: 
  # schedule: #UTC+0               #UTC+8
  #   - cron: '*/35 0-8 * * 1-5'   #工作日 上午8:00 - 下午4:00
  #   - cron: '*/25 8-14 * * 1-5'  #工作日 下午4:00 - 晚上10:00
  #   - cron: '*/55 14-21 * * 1-4' #工作日 晚上10:00 - 次日凌晨5:00
  #   - cron: '*/25 21-23 * * 1-5' #工作日 次日凌晨5:00 - 次日上午8:00
  #   - cron: '*/25 14-21 * * 5'   #星期五 晚上10:00 - 次日凌晨5:00
  #   - cron: '*/25 * * * 0,6'     #休息日 全天候
  # repository_dispatch: #https://www.chenshaowen.com/blog/how-to-trigger-github-action-remotely.html
    # types:
      # - Webhook
  workflow_dispatch: #手动调试按钮

jobs:
  filter-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build and Run
        run: go run main.go

      - name: Save Filtered Clash Config
        run: |
          # 从 main.go 中生成的 clash.yaml 复制到指定路径
          cp clash.yaml clash.yaml

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add /path/to/save/clash.yaml
          git commit -m "Update Clash config"
          git push
